### ISSUE TITLE
Update Cake.ExtractLicenses to target Cake v2.0.0

### ISSUE THREAD

**Issue by augustoproiete** [wgnf/liz#128]
[Cake 2.0.0](https://cakebuild.net/blog/2021/11/cake-v2.0.0-released) has been released  🎉

**Comment by wgnf** [comment]
probably won't do, as it makes sense to upgrade to cake version 3 directly. but i'll have a look at that

**Comment by wgnf** [comment]
decided not to support 2.0, will upgrade to 3.0 directly (current implementation targets 0.38.x so it can generally be used in cake 2.x)

**Comment by augustoproiete** [comment]
Superseded by https://github.com/wgnf/liz/issues/129
