### ISSUE TITLE
Update Cake.ExtractLicenses to target Cake v3.0.0

### ISSUE THREAD

**Issue by augustoproiete** [wgnf/liz#129]
[Cake 3.0.0](https://cakebuild.net/blog/2022/11/cake-v3.0.0-released) has been released  🎉

**Comment by wgnf** [comment]
Upgraded to Cake 3.0.0 with version 2.0.0, see: https://github.com/wgnf/liz/releases/tag/v2.0.0

**Comment by augustoproiete** [comment]
Awesome. Thank you!
