### ISSUE TITLE
Export Package + License-Details in a JSON-Format

### ISSUE THREAD

**Issue by wgnf** [wgnf/liz#16]

**Comment by tarekmansour** [comment]
Hi @wgnf,
What do you think about starting contributing with this enhancement issue?
if it's ok, could you please provide more details? such us: 
- the json will be provided through a web api or just on the console output
- what are the target output information we are expecting
- ... etc.

Thanks :)

**Comment by wgnf** [comment]
Hey Tarek,

Because this Tool (which will contain 3 tools: dotnet-CLI-Tool, Cake-AddIn (see https://cakebuild.net) and Nuke-AddIn (see https://nuke.build)) is meant for projects to extract and validate the licenses for the packages they're dependent on (preferably run in a CI/CD pipeline) this output as a JSON File would be one of the few ways to consume the information that are gathered by the tool.

So after the Pipeline (Project/Solution Input -> Extract Projects -> Extract Dependencies -> Extract Licenses) is done, this would output a JSON File (provided by the [ExtractLicensesSettings](https://github.com/wgnf/dotnet-nuget-licenses/blob/main/src/Core/DotnetNugetLicenses.Core/Settings/ExtractLicensesSettings.cs) and a CLI argument (I thought something like `--output-json`).

But the Pipeline is not completed yet and with that we/I don't know what information are meant to be exported for now.

With that being said, I don't think that's the best starting point for now, as this should be done later on, when the Pipeline is (nearly) finished.

I'd suggest you take a look at #5. Let me know what you think about that and hit me up when you need any help/direction

**Comment by wgnf** [comment]
merged into release branch
